#!/bin/zsh
# This hook is run after a new project is activated.
git init
echo "# ${PWD##*/}" > README.md
cp ~/.dotfiles/python/gitignore.default .gitignore
git add README.md .gitignore
git commit -m 'initialize new project'

